### ISSUE TITLE
Add links to example queries

### ISSUE THREAD

**Issue by equivalentideas** [Mermade/morph-proxy#1]
After I configured the service in Heroku, it builds, then I get a link to "View".

Now I want to access the data and see it in action 🎊  I click the view link and it takes you back to this Github repo.

Could it be more helpful to have a page with some links to example queries? or even a query builder? Something to help me immediately understand how it works and start using it.

Great work on this @MikeRalphson

**Comment by MikeRalphson** [comment]
@equivalentideas Thanks. Yes, I think there's more that can be done here. I'll take a look at what would be helpful, but the person deploying the proxy already knows their data better than the proxy will, and presumably has already used the Morph.io API successfully.

I'm constrained by the same reasons [this page](https://morph.io/documentation/api?scraper=MikeRalphson%2FNitro9) doesn't feature example queries beyond `select * from data` or a query builder; the proxy can (should) work for any scraper.

There is also a slight privacy concern in having example queries or a query builder exposed on the open internet, but I think this could be mitigated by having a way to switch off the landing page with a Heroku environment variable after deployment.

**Comment by MikeRalphson** [comment]
@equivalentideas Test query page and query builder are now the default landing page for the morph-proxy.

I guess the next stage is to add some dynamic code samples.

**Comment by equivalentideas** [comment]
> I guess the next stage is to add some dynamic code samples.

Yeah nice once @MikeRalphson 👍  . Already I get a much clearer idea and what I can do with this immediately.

**Comment by MikeRalphson** [comment]
@equivalentideas code samples added, ~~stolen~~ adapted from Morph.io, if that's ok?

**Comment by equivalentideas** [comment]
> if that's ok?

That's what they're there for :) Maybe give a shout out to folks who contributed those somewhere?

**Comment by MikeRalphson** [comment]
Good idea. Will have a hunt / git blame.

**Comment by MikeRalphson** [comment]
Credits added for @mlandauer as per git blame.
